module1:week 4 - Mobile-menu
uno36/Portfolio pull request #10
Opened 2023-04-10 09:49 UTC by uno36

1. created a new branch
2. created a file script.js
3. made javascript code to toggle class list

2023-04-11 13:38 UTC, Ibizugbe requested changes
Hi @uno36 👋👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/231177326-42121e53-9d43-49c8-94c8-9aa5f838f974.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] On desktop size the hamburger menu button is not visible and it becomes visible on mobile👍.
- [x]  [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript), [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) has been correctly setup and they are passing👍.
- [x] When the user clicks (or taps) the hamburger button, the mobile menu appears and when the user clicks or taps the `x` button, the mobile menu disappears👍.
- [x] When the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed👍.
- [x] When the user clicks (or taps) any option of the mobile menu, the mobile menu disappears👍.
- [x] Nice animation and UI👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] Nice work on your commit messages as they are descriptive😉 but we can improve them by ensuring they are always capitalised😉 you can take a look at[ this lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more clarity😉

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 13:38 UTC, Ibizugbe commented on styles.css
> +}
Nice job on implementing the functionalities of the mobile menu👍😉 But we have just a little bit of improvement relating to sticking to [the design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=nSrU7uvc0RxW1agh-0) as this is a requirement for [this milestone](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md)😉. Kindly take note of the comparison given below😉

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="320" alt="yours" src="https://user-images.githubusercontent.com/64643995/231175874-b7d321ba-fb39-4b60-a4df-497f913051f6.png">|<img width="292" alt="design menu" src="https://user-images.githubusercontent.com/64643995/231176025-b558b24d-4497-49a4-b720-805d57d882b6.png">|

kindly take note of the font properties (color) and background color😉 and make the necessary change👍

2023-04-11 14:54 UTC, divinecharlotte approved these changes
# Hello @uno36      😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- No linters errors ✔️
- Descriptive PR ✔️





## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-17 13:45 UTC, souad988 approved these changes
Hi @uno36 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔Good design
✔Good documentation(PR title , commit messages)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 08:33 UTC, merged